[tool.poetry]
name = "evnex"
version = "0.3.9"
description = "A Python wrapper for the EVNEX Cloud API"
authors = ["Brian Thorne <brian@hardbyte.nz>"]
readme = "README.md"
repository = "https://github.com/hardbyte/python-evnex"
license = "Apache-2.0"

[tool.poetry.urls]
issues = "https://github.com/hardbyte/python-evnex/issues"


[tool.poetry.dependencies]
python = "^3.11"
httpx = ">=0.23"
pycognito = ">2023.5.0,<2025"
boto3 = "^1.26"
pydantic = ">1.10"
tenacity = "^8.1"


[tool.poetry.group.dev.dependencies]
ruff = ">=0.1.4,<0.3.0"
isort = "^5.10.1"
pytest = ">7.1,<9.0"
pre-commit = "^3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
