[tool.poetry]
name = "evnex"
version = "0.2.3"
description = ""
authors = ["Brian Thorne <brian@hardbyte.nz>"]

[tool.poetry.dependencies]
python = "^3.10"
httpx = "^0.23.0"
pycognito = "^2022.8.0"
pydantic = "^1.10.1"
tenacity = "^8.0.1"
structlog = "^22.1.0"


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
